Repository UMC-7th/Front_Android, pull requests merged in 2025-02, with the labels that each got.

#37 Feat/#36 feat price fruit
  .idea/.name
  app/src/main/java/com/example/umc/Quote/FruitPriceActivity.kt
  app/src/main/java/com/example/umc/Quote/GridRecyclerViewAdapter.kt
  app/src/main/java/com/example/umc/Quote/HorizontalRecyclerViewAdapter.kt
  app/src/main/res/drawable/backimage.png
  app/src/main/res/drawable/card_background.xml
  app/src/main/res/drawable/custom_scroll_indicator.xml
  app/src/main/res/drawable/dietimage.png
  app/src/main/res/drawable/ic_arrow_down.xml
  app/src/main/res/drawable/myimage.png
  app/src/main/res/drawable/previous.png
  app/src/main/res/drawable/pricefruitimg.png
  app/src/main/res/drawable/priceimage.png
  app/src/main/res/drawable/subscribeimage.png
  app/src/main/res/drawable/subsctibecircle.png
  app/src/main/res/layout/activity_fruit_price.xml
  app/src/main/res/layout/item_grid.xml
  app/src/main/res/layout/item_horizontal.xml
Labels: FEAT, 🐰희원🐰

#50 [Feat]회원정보 조회연동
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragmentInfo.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/java/com/example/umc/UserApi/GetUserApi.kt
  app/src/main/java/com/example/umc/UserApi/LoginResponse.kt
  app/src/main/java/com/example/umc/UserApi/RetrofitClient.kt
  app/src/main/java/com/example/umc/UserApi/UserApi.kt
  app/src/main/java/com/example/umc/UserApi/UserProfileResponse.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
  app/src/main/res/drawable/ic_eye_invisible.png
  app/src/main/res/drawable/info_plus.png
  app/src/main/res/drawable/my_info.png
  app/src/main/res/drawable/my_info_change.png
  app/src/main/res/drawable/my_info_done.png
  app/src/main/res/drawable/my_info_naver.png
  app/src/main/res/drawable/my_info_small.png
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_info.xml
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#54 "[Feat/#51]유저 정보 수정"
  app/src/main/java/com/example/umc/Mypage/MyFragmentInfo.kt
  app/src/main/java/com/example/umc/UserApi/RetrofitClient.kt
  app/src/main/java/com/example/umc/UserApi/UpdateUserApi.kt
  app/src/main/java/com/example/umc/UserApi/UpdateUserRequest.kt
  app/src/main/java/com/example/umc/UserApi/UpdateUserResponse.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#57 Add/56 UI수정
  app/src/main/java/com/example/umc/SignUp/SigninEmailFragment.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/res/drawable/auto_login.png
  app/src/main/res/drawable/auto_login_on.png
  app/src/main/res/drawable/ic_delete_img.png
  app/src/main/res/drawable/ic_logout.png
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_info.xml
  app/src/main/res/layout/fragment_signin.xml
  app/src/main/res/layout/fragment_signin_email.xml
  app/src/main/res/layout/fragment_signin_info.xml
  app/src/main/res/layout/fragment_signin_nickname.xml
  app/src/main/res/layout/fragment_signin_phone.xml
  app/src/main/res/layout/fragment_signup.xml
Labels: ADD➕, 🐻‍❄️주완🐻‍❄️

#60 [FEAT/#59] 설문조사 ui 구현
  app/src/main/java/com/example/umc/Survey/SurveyAllergyBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyAllergyFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyBmiFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyDiseaseBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyDiseaseFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyExerciseBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyGoalWeightFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyHeightWeightFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyMealFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyPeopleFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyWorkFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyYearFragment.kt
  app/src/main/res/drawable/survey_bg_bottom_sheet.xml
  app/src/main/res/drawable/survey_edittext_button.xml
  app/src/main/res/drawable/survey_progressbar.xml
  app/src/main/res/drawable/survey_selected_item_background.xml
  app/src/main/res/drawable/surveyx.png
  app/src/main/res/layout/fragment_survey_allergy.xml
  app/src/main/res/layout/fragment_survey_allergy_bottom_sheet.xml
  app/src/main/res/layout/fragment_survey_bmi.xml
  app/src/main/res/layout/fragment_survey_disease.xml
  app/src/main/res/layout/fragment_survey_disease_bottom_sheet.xml
  app/src/main/res/layout/fragment_survey_exercise_bottom_sheet.xml
  app/src/main/res/layout/fragment_survey_goal_weight.xml
  app/src/main/res/layout/fragment_survey_height_weight.xml
  app/src/main/res/layout/fragment_survey_meal.xml
  app/src/main/res/layout/fragment_survey_people.xml
  app/src/main/res/layout/fragment_survey_work.xml
  app/src/main/res/layout/fragment_survey_year.xml
Labels: FEAT, 🐰희원🐰

#70 [ADD] #63 survey 코드 수정 및 연결
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Survey/SurveyAllergyBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyAllergyFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyBmiFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyDiseaseBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyDiseaseFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyExerciseBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyGoalFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyGoalWeightFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyHeightWeightFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyMealFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyPeopleFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyWorkFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyYearFragment.kt
  app/src/main/res/layout/activity_survey_container.xml
  app/src/main/res/layout/fragment_quote_sub.xml
  app/src/main/res/layout/fragment_signin.xml
  app/src/main/res/layout/fragment_survey_goal.xml
  app/src/main/res/values/styles.xml
Labels: ADD➕, 🐻‍❄️주완🐻‍❄️

#73 Chore/71
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/res/drawable/ic_delete_re.png
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_info.xml
  app/src/main/res/layout/fragment_signin.xml
  app/src/main/res/layout/fragment_subscribe_payment.xml
  app/src/main/res/values/styles.xml
Labels: ADD➕, CHORE, 🐻‍❄️주완🐻‍❄️

#75 Feat.74 마이페이지 알림, 변경 dialog추가
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragmentInfo.kt
  app/src/main/java/com/example/umc/Mypage/MyFragmentalarm.kt
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_alarm.xml
  app/src/main/res/layout/fragment_my_dialog.xml
  app/src/main/res/layout/fragment_my_info.xml
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#79 Feat/76
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/AnimationFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragmentInfo.kt
  app/src/main/java/com/example/umc/Onboarding/MyActivity.kt
  app/src/main/java/com/example/umc/Quote/PriceFragment.kt
  app/src/main/java/com/example/umc/Quote/Sub/FruitFragment.kt
  app/src/main/java/com/example/umc/Quote/Sub/MeatFragment.kt
  app/src/main/java/com/example/umc/Quote/Sub/QuoteFragmentSub.kt
  app/src/main/java/com/example/umc/Quote/Sub/SeafoodFragment.kt
  app/src/main/java/com/example/umc/Quote/Sub/TabpagerAdapter.kt
  app/src/main/java/com/example/umc/Quote/Sub/VegetableFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninInfoFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninNicknameFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninPhoneFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/java/com/example/umc/Survey/SurveyWorkFragment.kt
  app/src/main/java/com/example/umc/UserApi/APi/GetUserApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/KakaoLoginApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/OtpApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/OtpValidationApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/UpdateUserApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/UserApi.kt
  app/src/main/java/com/example/umc/UserApi/Request/LoginRequest.kt
  app/src/main/java/com/example/umc/UserApi/Request/OtpRequest.kt
  app/src/main/java/com/example/umc/UserApi/Request/OtpValidationRequest.kt
  app/src/main/java/com/example/umc/UserApi/Request/SignUpRequest.kt
  app/src/main/java/com/example/umc/UserApi/Request/UpdateUserRequest.kt
  app/src/main/java/com/example/umc/UserApi/Response/LoginResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/OtpResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/OtpValidationResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/SignUpResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/SuccessResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/SuccessValiResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/UpdateUserResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/UserProfileResponse.kt
  app/src/main/java/com/example/umc/UserApi/RetrofitClient.kt
  app/src/main/java/com/example/umc/UserApi/SignUpViewModel.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
  app/src/main/java/com/example/umc/UserApi/Viewmodel/LoginViewModel.kt
  app/src/main/java/com/example/umc/UserApi/Viewmodel/SignUpViewModel.kt
  app/src/main/res/drawable/dot_active_anmi.xml
  app/src/main/res/drawable/ic_anima_1.png
  app/src/main/res/drawable/ic_anima_2.png
  app/src/main/res/drawable/ic_anima_3.png
  app/src/main/res/drawable/ic_anima_4.png
  app/src/main/res/drawable/ic_anima_5.png
  app/src/main/res/layout/activity_diet.xml
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/activity_onboardingmain.xml
  app/src/main/res/layout/activity_price.xml
  app/src/main/res/layout/activity_subscribe.xml
  app/src/main/res/layout/fragment_animation.xml
  app/src/main/res/layout/fragment_quote_sub.xml
  settings.gradle.kts
Labels: ADD➕, 🐻‍❄️주완🐻‍❄️

#83 [Mod/#78] 온보딩 코드 수정
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/Onboarding/DietActivity.kt
  app/src/main/java/com/example/umc/Onboarding/MyActivity.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingDietFragment.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingMainActivity.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingMainFragment.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingMyFragment.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingPriceFragment.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingSubscribeFragment.kt
  app/src/main/java/com/example/umc/Onboarding/PriceActivity.kt
  app/src/main/java/com/example/umc/Onboarding/SubscribeActivity.kt
  app/src/main/res/drawable/dietimage.png
  app/src/main/res/drawable/myimage.png
  app/src/main/res/drawable/priceimage.png
  app/src/main/res/drawable/subscribeimage.png
  app/src/main/res/layout/activity_onboardingmain.xml
  app/src/main/res/layout/fragment_onboarding_diet.xml
  app/src/main/res/layout/fragment_onboarding_my.xml
  app/src/main/res/layout/fragment_onboarding_price.xml
  app/src/main/res/layout/fragment_onboarding_subscribe.xml
  app/src/main/res/layout/fragment_onboardingmain.xml
Labels: MOD, 🐰희원🐰

#92 Feat/88 User APi ( 식단조회, 건강점수 조회, 진단결과 조회, 프로필 이미지 조회)
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/Main/MainActivity.kt
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragmentInfo.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/java/com/example/umc/Subscribe/AddressViewModel.kt
  app/src/main/java/com/example/umc/Subscribe/Repository/AddressRepository.kt
  app/src/main/java/com/example/umc/Subscribe/Repository/DeliveryAddressRepository.kt
  app/src/main/java/com/example/umc/Subscribe/Retrofit/RetrofitClient.kt
  app/src/main/java/com/example/umc/Subscribe/RetrofitClient.kt
  app/src/main/java/com/example/umc/Subscribe/SubAddressAdapter.kt
  app/src/main/java/com/example/umc/Subscribe/SubAddressFragment.kt
  app/src/main/java/com/example/umc/Subscribe/SubcribeApi/DeliveryAddressApi.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeRequest/DeliveryAddressRequest.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeRequest/DeliveryAddressputRequest.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Get/DeliveryAddressGetresponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Get/DeliveryGetResponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Get/SuccessDeliveryResponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Post/DeliveryAddressresponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Post/SuccessAddressResponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Put/DeliveryAddressPutresponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Put/DeliveryPutResponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Put/SuccessDelivertPutResponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubsribeCart.kt
  app/src/main/java/com/example/umc/UserApi/APi/DiagnosisApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/HealthscoreApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/ImageProfileApi.kt
  app/src/main/java/com/example/umc/UserApi/APi/MypageGoalApi.kt
  app/src/main/java/com/example/umc/UserApi/Response/DiagnosisResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/HealthScoreResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/MypageGoalResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/UserImageResponse.kt
  app/src/main/java/com/example/umc/UserApi/RetrofitClient.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
  app/src/main/res/drawable/ic_mypage_down.png
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_image_dialog.xml
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#94 [Mod/#77] diet api
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/Diet/DailyDietFragment.kt
  app/src/main/java/com/example/umc/Diet/DailyHomeFragment.kt
  app/src/main/java/com/example/umc/Diet/DietDetailFragment.kt
  app/src/main/java/com/example/umc/Diet/MenuItem.kt
  app/src/main/java/com/example/umc/Diet/MenuItemAdapter.kt
  app/src/main/java/com/example/umc/Diet/meal/MealViewModel.kt
  app/src/main/java/com/example/umc/Diet/meal/MealViewModelFactory.kt
  app/src/main/java/com/example/umc/Subscribe/SubsribeCart.kt
  app/src/main/java/com/example/umc/model/repository/MealRepository.kt
  app/src/main/java/com/example/umc/model/request/PostDailyMealRequest.kt
  app/src/main/java/com/example/umc/model/request/PostRefreshMealRequest.kt
  app/src/main/java/com/example/umc/model/response/PostDailyMealResponse.kt
  app/src/main/java/com/example/umc/model/response/PostMealRefreshResponse.kt
  app/src/main/java/com/example/umc/model/service/MealApiService.kt
  app/src/main/res/layout/fragment_diet_detail.xml
Labels: ADD➕, MOD

#102 Feat/#99
  README.md
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragmentInfo.kt
  app/src/main/java/com/example/umc/SignUp/SigninPhoneFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Subscribe/Repository/MealRepository.kt
  app/src/main/java/com/example/umc/Subscribe/Retrofit/RetrofitClient.kt
  app/src/main/java/com/example/umc/Subscribe/SubcribeApi/MealApi.kt
  app/src/main/java/com/example/umc/Subscribe/SubscribeResponse/Meal/MealResponse.kt
  app/src/main/java/com/example/umc/Subscribe/SubscriptionHistoryFragment.kt
  app/src/main/java/com/example/umc/UserApi/APi/UserApi.kt
  app/src/main/java/com/example/umc/UserApi/Request/UpdateUserNameRequest.kt
  app/src/main/java/com/example/umc/UserApi/Response/UpdateNicknameResponse.kt
  app/src/main/java/com/example/umc/UserApi/SharedPreferencesManager.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
  app/src/main/res/layout/fragment_my.xml
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#103 [Add/#87] 설문조사 api
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Survey/RetrofitClient.kt
  app/src/main/java/com/example/umc/Survey/SurveyAllergyBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyAllergyFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyApiService.kt
  app/src/main/java/com/example/umc/Survey/SurveyBmiFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyData.kt
  app/src/main/java/com/example/umc/Survey/SurveyDiseaseBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyDiseaseFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyExerciseBottomSheetFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyGoalFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyGoalWeightFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyHeightWeightFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyMealFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyPeopleFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyViewModel.kt
  app/src/main/java/com/example/umc/Survey/SurveyWorkFragment.kt
  app/src/main/java/com/example/umc/Survey/SurveyYearFragment.kt
  app/src/main/java/com/example/umc/Survey/UserRepository.kt
Labels: ADD➕, 🐰희원🐰

#108 [Add] naver api , 회원가입 수정, 마이페이지 api 수정, name 수정
  .gitignore
  .idea/deploymentTargetSelector.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/Diet/HomeContainerFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragmentInfo.kt
  app/src/main/java/com/example/umc/SignUp/SigninNicknameFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/java/com/example/umc/Subscribe/SubAddressAdapter.kt
  app/src/main/java/com/example/umc/Subscribe/SubFragment.kt
  app/src/main/java/com/example/umc/Subscribe/SubscriptionManageFragment.kt
  app/src/main/java/com/example/umc/UserApi/APi/NaverLoginApi.kt
  app/src/main/java/com/example/umc/UserApi/Naver/NaverLoginResponse.kt
  app/src/main/java/com/example/umc/UserApi/NaverLoginManager.kt
  app/src/main/java/com/example/umc/UserApi/Response/HealthScoreResponse.kt
  app/src/main/java/com/example/umc/UserApi/Response/LoginResult.kt
  app/src/main/java/com/example/umc/UserApi/Response/SignUpResponse.kt
  app/src/main/java/com/example/umc/UserApi/RetrofitClient.kt
  app/src/main/java/com/example/umc/UserApi/SharedPreferencesManager.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
  app/src/main/java/com/example/umc/UserApi/Viewmodel/SignUpViewModel.kt
  app/src/main/res/layout/fragment_my_image_dialog.xml
  app/src/main/res/layout/fragment_signin.xml
  app/src/main/res/layout/fragment_subscription_manage.xml
  app/src/main/res/values/secrets.xml
  gradle/libs.versions.toml
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#114 Add/109 애니메이션, 마이페이지, 구독 UI 수정
  app/src/main/java/com/example/umc/AnimationFragment.kt
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninNicknameFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Survey/SurveyExerciseBottomSheetFragment.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
  app/src/main/res/layout/fragment_animation.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_info.xml
  app/src/main/res/raw/loading.json
Labels: ADD➕, 🐻‍❄️주완🐻‍❄️

#117 [MOD/#110] 온보딩 버튼 수정
  app/src/main/java/com/example/umc/Onboarding/OnboardingMyFragment.kt
  app/src/main/res/layout/fragment_onboarding_diet.xml
  app/src/main/res/layout/fragment_onboarding_my.xml
  app/src/main/res/layout/fragment_onboarding_price.xml
  app/src/main/res/layout/fragment_onboarding_subscribe.xml
Labels: MOD, 🐰희원🐰

#118 "[Add/#116] UI 수정"
  app/src/main/java/com/example/umc/AnimationFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/java/com/example/umc/Subscribe/SubAddressFragment.kt
  app/src/main/res/layout/fragment_animation.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_my_dialog.xml
  app/src/main/res/layout/fragment_my_info.xml
  app/src/main/res/layout/fragment_signin.xml
Labels: ADD➕, 🐻‍❄️주완🐻‍❄️
