Repository UMC-7th/Front_Android, pull requests merged in 2025-01, with the labels that each got.

#2 [INIT/#1] 프로젝트 초기설정
  app/src/main/res/drawable/ic_ellipse.xml
  app/src/main/res/drawable/ic_octagon.xml
  app/src/main/res/drawable/ic_plus.xml
  app/src/main/res/drawable/ic_square.xml
  app/src/main/res/drawable/img_hat.png
  app/src/main/res/drawable/img_hat1.png
  app/src/main/res/drawable/img_hat2.png
  app/src/main/res/drawable/img_hat3.png
  app/src/main/res/drawable/shadow_level1.xml
  app/src/main/res/drawable/shadow_level2.xml
  app/src/main/res/drawable/shadow_level3.xml
  app/src/main/res/drawable/shadow_level4.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
Labels: INIT, 🐵규현🐵

#6 [Feat#1][Splash,SignIn,SignUp
  .idea/misc.xml
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/Main/MainActivity.kt
  app/src/main/java/com/example/umc/MainActivity.kt
  app/src/main/java/com/example/umc/SignUp/SignUpFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninEmailFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninInfoFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninNicknameFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninPhoneFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/res/drawable/gradient_background.xml
  app/src/main/res/drawable/main_button_color.xml
  app/src/main/res/drawable/radius_button.xml
  app/src/main/res/drawable/rounded_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/signin.xml
  app/src/main/res/layout/signin_email.xml
  app/src/main/res/layout/signin_info.xml
  app/src/main/res/layout/signin_nickname.xml
  app/src/main/res/layout/signin_phone.xml
  app/src/main/res/layout/signup.xml
  app/src/main/res/layout/splash.xml
  app/src/main/res/menu/bottom_navigation.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#8 "fix#1-loginactivity 비밀번호 표시,가리기"
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/res/layout/signin.xml
  app/src/main/res/layout/splash.xml
Labels: FIX

#10 [ADD/#4] 월간, 하루 Fragment 생성
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/DailyHomeFragment.kt
  app/src/main/java/com/example/umc/HomeContainerFragment.kt
  app/src/main/java/com/example/umc/HomePagerAdapter.kt
  app/src/main/java/com/example/umc/Main/MainActivity.kt
  app/src/main/java/com/example/umc/MenuItem.kt
  app/src/main/java/com/example/umc/MenuItemAdapter.kt
  app/src/main/java/com/example/umc/MonthlyHomeFragment.kt
  app/src/main/java/com/example/umc/MyFragment.kt
  app/src/main/java/com/example/umc/PriceFragment.kt
  app/src/main/java/com/example/umc/SignUp/SignUpFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninEmailFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninInfoFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninNicknameFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninPhoneFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/java/com/example/umc/SubFragment.kt
  app/src/main/res/color/btn_nav_menu_color.xml
  app/src/main/res/drawable/ic_back_btn.xml
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/drawable/ic_eye_visible.xml
  app/src/main/res/drawable/ic_google.xml
  app/src/main/res/drawable/ic_home.xml
  app/src/main/res/drawable/ic_kakao.xml
  app/src/main/res/drawable/ic_my.xml
  app/src/main/res/drawable/ic_naver.xml
  app/src/main/res/drawable/ic_price.xml
  app/src/main/res/drawable/ic_sub.xml
  app/src/main/res/drawable/ic_union2_login.xml
  app/src/main/res/drawable/img_google_btn.png
  app/src/main/res/drawable/img_kakao_btn.png
  app/src/main/res/drawable/img_naver_btn.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_daily_home.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/fragment_home_container.xml
  app/src/main/res/layout/fragment_monthly_home.xml
  app/src/main/res/layout/fragment_my.xml
  app/src/main/res/layout/fragment_price.xml
  app/src/main/res/layout/fragment_signin.xml
  app/src/main/res/layout/fragment_signin_email.xml
  app/src/main/res/layout/fragment_signin_info.xml
  app/src/main/res/layout/fragment_signin_nickname.xml
  app/src/main/res/layout/fragment_signin_phone.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/fragment_sub.xml
  app/src/main/res/layout/item_menu.xml
  app/src/main/res/layout/splash.xml
  app/src/main/res/menu/bottom_navigation.xml
  app/src/main/res/values/strings.xml
Labels: ADD➕, CHORE, FEAT, 🐵규현🐵

#12 [ADD/#11] 온보딩
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/DietActivity.kt
  app/src/main/java/com/example/umc/Main/MainActivity.kt
  app/src/main/java/com/example/umc/MyActivity.kt
  app/src/main/java/com/example/umc/PriceActivity.kt
  app/src/main/java/com/example/umc/SubscribeActivity.kt
  app/src/main/res/drawable/dot_active.xml
  app/src/main/res/drawable/dot_inactive.xml
  app/src/main/res/layout/activity_diet.xml
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/activity_onboardingmain.xml
  app/src/main/res/layout/activity_price.xml
  app/src/main/res/layout/activity_subscribe.xml
Labels: ADD➕, 🐰희원🐰

#19 Feat#18
  app/src/main/java/com/example/umc/Subscribe/SubsribeCart.kt
  app/src/main/res/drawable/add.png
  app/src/main/res/drawable/back2.png
  app/src/main/res/drawable/check_non.png
  app/src/main/res/drawable/check_on.png
  app/src/main/res/drawable/miner.png
  app/src/main/res/drawable/real_add.png
  app/src/main/res/drawable/sub_card.xml
  app/src/main/res/drawable/sub_img.png
  app/src/main/res/drawable/topcard.xml
  app/src/main/res/layout/fragment_subscribe_cart.xml
Labels: FEAT

#23 [Feat]#18구독 페이지(결제,장바구니)/시세 sub 페이지(xml)
  app/src/main/java/com/example/umc/Subscribe/SubsribeCart.kt
  app/src/main/java/com/example/umc/Subscribe/Subsribecredit.kt
  app/src/main/res/layout/fragment_subscribe_payment.xml
Labels: FEAT, 🐻‍❄️주완🐻‍❄️

#27 Add prototype
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/Diet/DailyHomeFragment.kt
  app/src/main/java/com/example/umc/Diet/DietDetailAdapter.kt
  app/src/main/java/com/example/umc/Diet/DietDetailFragment.kt
  app/src/main/java/com/example/umc/Diet/HomeContainerFragment.kt
  app/src/main/java/com/example/umc/Diet/HomePagerAdapter.kt
  app/src/main/java/com/example/umc/Diet/MenuItem.kt
  app/src/main/java/com/example/umc/Diet/MenuItemAdapter.kt
  app/src/main/java/com/example/umc/Diet/MonthlyHomeFragment.kt
  app/src/main/java/com/example/umc/Main/MainActivity.kt
  app/src/main/java/com/example/umc/Mypage/MyFragment.kt
  app/src/main/java/com/example/umc/Onboarding/DietActivity.kt
  app/src/main/java/com/example/umc/Onboarding/MyActivity.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingActivity.kt
  app/src/main/java/com/example/umc/Onboarding/PriceActivity.kt
  app/src/main/java/com/example/umc/Onboarding/SubscribeActivity.kt
  app/src/main/java/com/example/umc/Quote/PriceFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninNicknameFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/Splash/SplashActivity.kt
  app/src/main/java/com/example/umc/Subscribe/SubFragment.kt
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/activity_onboardingmain.xml
  app/src/main/res/layout/fragment_monthly_home.xml
  app/src/main/res/values/themes.xml
Labels: ADD➕, CHORE, 🐻‍❄️주완🐻‍❄️

#28 Feat#18+UI수정
  app/src/main/res/layout/fragment_signin.xml
  app/src/main/res/layout/fragment_signup.xml
  app/src/main/res/layout/splash.xml
Labels: ADD➕, 🐻‍❄️주완🐻‍❄️

#31 [MOD/#30] 온보딩 수정
  app/src/main/java/com/example/umc/Onboarding/DietActivity.kt
  app/src/main/java/com/example/umc/Onboarding/MyActivity.kt
  app/src/main/java/com/example/umc/Onboarding/OnboardingMainActivity.kt
  app/src/main/java/com/example/umc/Onboarding/PriceActivity.kt
  app/src/main/java/com/example/umc/Onboarding/SubscribeActivity.kt
  app/src/main/res/layout/activity_diet.xml
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/activity_onboardingmain.xml
  app/src/main/res/layout/activity_price.xml
  app/src/main/res/layout/activity_subscribe.xml
Labels: MOD, 🐰희원🐰

#32 "Feat/30 로그인,회원가입 APi 연결 (re)"
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/example/umc/SignUp/SignUpFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninInfoFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninNicknameFragment.kt
  app/src/main/java/com/example/umc/SignUp/SigninPhoneFragment.kt
  app/src/main/java/com/example/umc/Signin/LoginActivity.kt
  app/src/main/java/com/example/umc/UserApi/LoginRequest.kt
  app/src/main/java/com/example/umc/UserApi/LoginResponse.kt
  app/src/main/java/com/example/umc/UserApi/LoginViewModel.kt
  app/src/main/java/com/example/umc/UserApi/RetrofitClient.kt
  app/src/main/java/com/example/umc/UserApi/SignUpRequest.kt
  app/src/main/java/com/example/umc/UserApi/SignUpResponse.kt
  app/src/main/java/com/example/umc/UserApi/SignUpViewModel.kt
  app/src/main/java/com/example/umc/UserApi/UserApi.kt
  app/src/main/java/com/example/umc/UserApi/UserRepository.kt
  app/src/main/res/xml/network_security_config.xml
Labels: ADD➕, FEAT, 🐻‍❄️주완🐻‍❄️

#34 "quote img 추가"
  app/src/main/res/drawable/banana.jpg
  app/src/main/res/drawable/mandarin.jpg
  app/src/main/res/drawable/shine.jpg
  app/src/main/res/drawable/strawberry.jpg
  app/src/main/res/drawable/tomato.jpg
Labels: CHORE, 🐻‍❄️주완🐻‍❄️
